apiVersion: v2
name: canonical-openstack-foundations
version: 0.15.0
description: A Helm chart for the Canonical OpenStack Foundations training site
appVersion: 0.15.0
dependencies:
  - name: redis
    version: "18.1.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
